import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	aumaticSidebar: [{ type: "autogenerated", dirName: "." }],

	// candidationSidebar: [
	// 	{
	// 		type: "category",
	// 		label: "Candidatura", // The label for the folder in the sidebar
	// 		items: [
	// 			{
	// 				type: "autogenerated",
	// 				dirName: "Candidatura", // Path to the folder relative to `docs/`
	// 			},
	// 		],
	// 	},
	// ],
	// RTBSidebar: [
	// 	{
	// 		type: "category",
	// 		label: "RTB", // The label for the folder in the sidebar
	// 		items: [
	// 			{
	// 				type: "autogenerated",
	// 				dirName: "RTB", // Path to the folder relative to `docs/`
	// 			},
	// 		],
	// 	},
	// ],
	// PBSiderbar: [
	// 	{
	// 		items: [
	// 			{
	// 				type: "autogenerated",
	// 				dirName: "PB", // Path to the folder relative to `docs/`
	// 			},
	// 		],
	// 	},
	// ],

	// But you can create a sidebar manually
	// tutorialSidebar: [
	// 	"intro",
	// 	"hello",
	// 	{
	// 		type: "category",
	// 		label: "Tutorial",
	// 		items: ["tutorial-basics/create-a-document"],
	// 	},
	// ],
};

export default sidebars;
