name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  create-glossary:
    name: Build Glossary
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: "docs/package-lock.json"
      
      - name: Install dependencies
        run: npm ci

      - name: Create Glossary
        run: |
          npm run postinstall
          npm run docusaurus parse
          npm run docusaurus glossary
          ls -la
          cat ./docs/RTB/Glossario.md

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: complete_source
          path: ./

  build-pdf:
    needs: create-glossary
    name: Build Pdfs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: complete_source

      - name: Install LaTeX
        run: |
          sudo apt-get update && \
          sudo apt-get install -y texlive-base texlive-lang-italian texlive-fonts-recommended texlive-latex-extra

      - name: Identify modified .tex files
        id: modified-files
        run: |
          git diff --name-only HEAD^ HEAD | grep '^docs/.*\.md$' | sed 's|^docs/||' > modified_files.txt || true

      - uses: pandoc/actions/setup@v1
        with:
            version: 3.5
            
      - name: Compile PDF
        run: |
            ./compile-pdf.sh
            
      - name: Debug
        run: | 
          ls -la
          ls -la docs

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-docs
          path: ./

  build:
    needs: build-pdf
    name: Build Docusaurus
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-docs
          
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: "docs/package-lock.json"

      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build

      - name: Debug
        run: ls -la

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

  commit:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write 
      id-token: write 

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4