name: Test build

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          working-directory: docs

      - name: List directory contents for debugging
        run: ls -la docs  # This will show the contents of the 'docs' folder

      - name: Show PWD
        run: pwd

      - name: Install dependencies
        run: npm ci
        working-directory: docs  # Set working directory to 'docs' folder

      - name: Test build website
        run: npm run build
        working-directory: docs  # Ensure the build is run from the 'docs' folder
