name: Test build

on:
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: docs
      - name: Test build website
        run: npm run build
        working-directory: docs
